use_frameworks!

platform :ios, '13.0'

use_frameworks! :linkage => :static

target 'BreadPartnersSDK_Example' do
  pod 'BreadPartnersSDK', :path => '../'

  target 'BreadPartnersSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end

   post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end