name: Run Unit Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Xcode
        run: |
          sudo xcode-select --install || true

      - name: Print 
        run: xcodebuild -list

      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -workspace BreadPartnersSDK.xcworkspace \
            -scheme BreadPartnersSDK_Tests \
            -destination 'platform=iOS Simulator,name=iPhone 17'